### ISSUE TITLE
so# premium videos support

### ISSUE THREAD

**Issue by dado330** [AlexAplin/nndownload#102]
I'm trying to retrieve the comments, metadata and thumbnail from so35736631.

First, I'm not a Premium member but I'm connected through a proxy server in Japan. (NordVPN)

This is the command I'm running:

```cmd
python nndownload.py https://www.nicovideo.jp/watch/so35736631 -u MYEMAIL -l -o /tmp/{id}.{ext} -m -t -c -s
```

On a normal video it works fine but for this particular one it raise an error.

This is the log:

```cmd
2021-04-29 22:11:25,151 INFO: Logging in...
2021-04-29 22:11:29,853 INFO: Logged in.
2021-04-29 22:11:35,309 ERROR: TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Python39\Lib\site-packages\nndownload\nndownload.py", line 1608, in main
    process_url_mo(session, url_mo)
  File "C:\Python39\Lib\site-packages\nndownload\nndownload.py", line 1570, in process_url_mo
    request_video(session, url_id)
  File "C:\Python39\Lib\site-packages\nndownload\nndownload.py", line 883, in request_video
    template_params = perform_api_request(session, document)
  File "C:\Python39\Lib\site-packages\nndownload\nndownload.py", line 1216, in perform_api_request
    if params["media"]["delivery"]["movie"].get("session"):
TypeError: 'NoneType' object is not subscriptable
```

Am I doing something wrong?

I don't want to download the video but just the comments and metadata which should be open even for a non premium user. Am i mistaken?

**Comment by AlexAplin** [comment]
@dado330 Official anime uploads work a bit differently than other uploads, namely encryption being applied to the videos. It may also be serving videos a different way than all other videos now (DMC). If possible, can you access the video on your VPN and copy the source of the page (right click -> View Page Source)?

**Comment by DavideMessinaARS** [comment]
In attachment the source of the video so31318264.  ([https _www.nicovideo.jp_watch_so31318264.txt](https://github.com/AlexAplin/nndownload/files/6429698/https._www.nicovideo.jp_watch_so31318264.txt))


With episode 1 (so31317998), which is open to normal users, I can download comments, thumbnails and metadata correctly.

**Comment by AlexAplin** [comment]
These videos should work with -s on now. Keeping this ticket open so we eventually can have media downloads working on all premium videos.

**Comment by KaIZeR99-code** [comment]
So I need to add -s arguments to download premium video?
