### ISSUE TITLE
Program crashed when login

### ISSUE THREAD

**Issue by oxygenkun** [AlexAplin/nndownload#125]
It's my first time to use nndownload. When I tried `nndownload <URL>`, it prompted email and password inputs. After I had done that, the program crashed.

```
Logging in...
Traceback (most recent call last):
  File "nndownload\nndownload.py", line 1816, in main
    session = login(account_username, account_password, session_cookie)
  File "nndownload\nndownload.py", line 1683, in login
    otp_code_account = otp_code_page.select("div.pageMainMsg span.userAccount")[0].text
IndexError: list index out of range
Traceback (most recent call last):
  File "nndownload\nndownload.py", line 1847, in <module>
    main()
  File "nndownload\nndownload.py", line 1816, in main
    session = login(account_username, account_password, session_cookie)
  File "nndownload\nndownload.py", line 1683, in login
    otp_code_account = otp_code_page.select("div.pageMainMsg span.userAccount")[0].text
IndexError: list index out of range
[97828] Failed to execute script 'nndownload' due to unhandled exception!
```

It seems that the parsing preocess for login page was failed.

**Comment by AlexAplin** [comment]
Some error occured on the OTP page. Are you still able to reproduce this? When you login from a browser, what sort of login flow do you go through (OTP page presented, not at all)?

**Comment by AlexAplin** [comment]
@oxygenkun Any update?

**Comment by AlexAplin** [comment]
Closing as no update from original reporter or any additional reports.
