### ISSUE TITLE
New comments API

### ISSUE THREAD

**Issue by shiren00** [AlexAplin/nndownload#127]
Could you please confirm this?
Video downloading is not a problem.

environment:
Japan, windows10, 64bit

command:
``nndownload_v1_12.exe https://www.nicovideo.jp/watch/sm9 -g -c -s``

log:
```
Proceeding with no login. Some videos may not be available for download or may only be available in a lower quality. For access to all videos, please provide a login with --username/--password or --netrc.
Downloading comments for sm9...
Traceback (most recent call last):
  File "urllib3\connection.py", line 174, in _new_conn
  File "urllib3\util\connection.py", line 72, in create_connection
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 398, in _make_request
  File "urllib3\connection.py", line 239, in request
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "urllib3\connection.py", line 205, in connect
  File "urllib3\connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000017826BADCF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 813, in urlopen
  File "urllib3\connectionpool.py", line 813, in urlopen
  File "urllib3\connectionpool.py", line 813, in urlopen
  [Previous line repeated 2 more times]
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='nmsg.nicovideo.jp', port=80): Max retries exceeded with url: /api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017826BADCF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nndownload\nndownload.py", line 1831, in main
  File "nndownload\nndownload.py", line 1779, in process_url_mo
  File "nndownload\nndownload.py", line 992, in request_video
  File "nndownload\nndownload.py", line 1615, in download_comments
  File "requests\sessions.py", line 590, in post
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='nmsg.nicovideo.jp', port=80): Max retries exceeded with url: /api (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017826BADCF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

**Comment by AlexAplin** [comment]
The comments API has changed to nvcomment.nicovideo.jp (or the older API expired).
