### ISSUE TITLE
OTP not always presented as expected

### ISSUE THREAD

**Issue by shiren00** [AlexAplin/nndownload#130]
- Run on Command Prompt on Win10 64bit
- nndownload Binaries v1.12.2 for Windows
- Input `nndownload_v1_12_2.exe --username "xxx" --password "xxx" https://www.nicovideo.jp/watch/sm9`

```
Logging in...
Traceback (most recent call last):
  File "nndownload\nndownload.py", line 1819, in main
  File "nndownload\nndownload.py", line 1686, in login
IndexError: list index out of range
Traceback (most recent call last):
  File "nndownload\nndownload.py", line 1853, in <module>
  File "nndownload\nndownload.py", line 1819, in main
  File "nndownload\nndownload.py", line 1686, in login
IndexError: list index out of range
[1724] Failed to execute script 'nndownload' due to unhandled exception!
```

**Comment by shiren00** [comment]
- I have not set two-factor authentication.

**Comment by AlexAplin** [comment]
The OTP code is presented regardless of whether two factor is enabled on the account.

- Do you see anything like this when you login from your browser, or do you go straight to the home page and show as logged in?
![2023-01-29 144030](https://user-images.githubusercontent.com/547786/215351828-7cc9b38d-b6a7-45b6-a5ca-50d8bbadfb1b.png)
- Does the same thing happen if you try a different browser (Firefox, Chrome, Edge)?
- Do you see any "saved" (trusted) devices on this page? https://account.nicovideo.jp/my/history/login

**Comment by shiren00** [comment]
In the first place, the browser does not appear. The python error message only.

>Do you see any "saved" (trusted) devices on this page? https://account.nicovideo.jp/my/history/login

I looked at the page, the login itself seems to be been.
It is contained in "valid access"(現在のアクセス) and "Login History"(ログイン履歴).

**Comment by AlexAplin** [comment]
Closing this as I believe #199 will have fixed this, now that we understand it's presented differently overseas
