### ISSUE TITLE
Comment download stopped working.

### ISSUE THREAD

**Issue by Lywzc** [AlexAplin/nndownload#141]
Downloading comments for so43262360...
Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 876, in urlopen
  File "urllib3\connectionpool.py", line 876, in urlopen
  File "urllib3\connectionpool.py", line 876, in urlopen
  [Previous line repeated 2 more times]
  File "urllib3\connectionpool.py", line 866, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nvcomment.nicovideo.jp', port=443): Max retries exceeded with url: /v1/threads (Caused by ResponseError('too many 503 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nndownload\nndownload.py", line 1833, in main
  File "nndownload\nndownload.py", line 1782, in process_url_mo
  File "nndownload\nndownload.py", line 992, in request_video
  File "nndownload\nndownload.py", line 1617, in download_comments
  File "requests\sessions.py", line 566, in options
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 507, in send
requests.exceptions.RetryError: HTTPSConnectionPool(host='nvcomment.nicovideo.jp', port=443): Max retries exceeded with url: /v1/threads (Caused by ResponseError('too many 503 error responses'))

Not sure why.

**Comment by Lywzc** [comment]
It seems the new comments api is nv-comment instead of nvcomment

**Comment by AlexAplin** [comment]
Thanks for the quck spot!
