### ISSUE TITLE
Can't download from manga.nicovideo.jp

### ISSUE THREAD

**Issue by starlightsys** [AlexAplin/nndownload#194]
Trying to download manga from manga.nicovideo.jp fails with a cryptic NPE.

## Environment
NixOS 24.11 (Vicuna) x86_64
shell.nix:
```nix
{
  pkgs ? import <nixpkgs> { },
}:
pkgs.mkShellNoCC {
  buildInputs =
    (with pkgs; [
      python312
    ])
    ++ (with pkgs.python312Packages; [
      aiohttp
      aiohttp-socks
      beautifulsoup4
      ffmpeg-python
      gevent
      mutagen
      pycryptodome
      requests
      rich
      setuptools
      urllib3
    ]);
}
```

## Steps to recreate
`python nndownload.py -g 'https://manga.nicovideo.jp/watch/mg662039?track=ct_episode'

## Expected
[*Potions (Zoku)* chapter 0](https://manga.nicovideo.jp/watch/mg662039?track=ct_episode) is downloaded.

## Observed
```
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/myusername/Documents/git/Public/nndownload/out/../nndownload.py", line 4, in <module>
    cli()
  File "/home/myusername/Documents/git/Public/nndownload/nndownload/nndownload.py", line 2215, in cli
    main()
  File "/home/myusername/Documents/git/Public/nndownload/nndownload/nndownload.py", line 2192, in main
    process_url_mo(session, url_mo)
  File "/home/myusername/Documents/git/Public/nndownload/nndownload/nndownload.py", line 2116, in process_url_mo
    download_manga_chapter(session, url_id)
  File "/home/myusername/Documents/git/Public/nndownload/nndownload/nndownload.py", line 726, in download_manga_chapter
    template_params = collect_seiga_manga_parameters(session, chapter_document, template_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myusername/Documents/git/Public/nndownload/nndownload/nndownload.py", line 687, in collect_seiga_manga_parameters
    bare_chapter_id = document.select_one("#full_watch_head_bar")["data-theme-id"]
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by starlightsys** [comment]
It works when logged in...  Never mind me, haha
