### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Lee-lithium** [AlexAplin/nndownload#60]
I download this manga get this issue.

>nndownload.py https://seiga.nicovideo.jp/comic/33772
Logging in...
Logged in.
Downloading comic 33772...
1/17
Traceback (most recent call last):
  File "D:\C_Drive\Users\usr\AppData\local\Programs\Python\Python37-32\Scripts\nndownload.py", line 1330, in <module>
    main()
  File "D:\C_Drive\Users\usr\AppData\local\Programs\Python\Python37-32\Scripts\nndownload.py", line 1318, in main
    process_url_mo(session, url_mo)
  File "D:\C_Drive\Users\usr\AppData\local\Programs\Python\Python37-32\Scripts\nndownload.py", line 1280, in process_url_mo
    download_manga(session, url_id)
  File "D:\C_Drive\Users\usr\AppData\local\Programs\Python\Python37-32\Scripts\nndownload.py", line 564, in download_manga
    download_manga_chapter(session, chapter_id)
  File "D:\C_Drive\Users\usr\AppData\local\Programs\Python\Python37-32\Scripts\nndownload.py", line 510, in download_manga_chapter
    template_params = collect_seiga_manga_parameters(document, template_params)
  File "D:\C_Drive\Users\usr\AppData\local\Programs\Python\Python37-32\Scripts\nndownload.py", line 496, in collect_seiga_manga_parameters
    template_params["uploader_id"] = SEIGA_USER_ID_RE.search(document.select("dd.user_name a")[0]["href"]).group(1)
IndexError: list index out of range

**Comment by AlexAplin** [comment]
You're using an older version of the script, this was fixed in 9431acfaf88bc2cf6d8e218d29c8d2a8899ec70e. Please update.

**Comment by Lee-lithium** [comment]
thank you very much, it's work :)
pip install nndownload, give me v1.3 version

**Comment by AlexAplin** [comment]
Sorry about that, I still need to push v1.4 soon!
