### ISSUE TITLE
No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by senneh** [AlexAplin/nndownload#82]
I get the following error trying to install by running `pip install nndownload`

```
$ pip install nndownload
Defaulting to user installation because normal site-packages is not writeable
Collecting nndownload
  Downloading nndownload-1.8.tar.gz (22 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wcsi49y7/nndownload_aa63157e628246d59bda28a6407b2ef4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wcsi49y7/nndownload_aa63157e628246d59bda28a6407b2ef4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-u62rbkw2
         cwd: /tmp/pip-install-wcsi49y7/nndownload_aa63157e628246d59bda28a6407b2ef4/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wcsi49y7/nndownload_aa63157e628246d59bda28a6407b2ef4/setup.py", line 8, in <module>
        with open("requirements.txt", "r") as requirements_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Fyi, cloning this repo and running ```$ pip install .``` does work. 

manually downloading and inspecting the package at https://pypi.org/project/nndownload/#files shows that requirements.txt is indeed not included in the package.

**Comment by AlexAplin** [comment]
Good looking out on that, fortunately only affecteed 1.8. Will merge in soon.
